### ISSUE TITLE
Not able to run this project

### ISSUE THREAD

**Issue by AwasthiMaddy** [yeleaveszi/Play-Videos-In-HDFS#2]
Hi 

I don't know exactly how to comment here on the github. So I am opening an issue, although I don't think there is an issue in your project. But I was not able to make it work. Find below the steps which I took to run your project & the error I faced. Any help in solving the error would be appreciated!
1. I stored a mp4 video (say a.mp4) in HDFS using put command. As per the instruction given by you in "Usage" section, I made the necessary modifications.  
2. Modified the namenode's IP & port in Constants.java . 
3. Modified the fpath parameter. I saved the video a.mp4 in the location '/a.mp4' in HDFS. So accordingly I changed the parameter & the http link became "http://localhost:8080/HDFSVideoDemo/stream?fpath=/a.mp4"
4. I then build the project using maven & so a WAR file named "HDFSVideoDemo-0.0.1-SNAPSHOT.war" was generated in the target folder in the root directory of the project.  
5. Then for deploying the web project in the web server, I copied the WAR file in the 'webapps' directory of tomcat & restarted the tomcat server.
6. Then when I visit the link 'http://localhost:8080/HDFSVideoDemo/MyStream.html' in the browser, I get the error of '404 - Resource not found'. Although tomcat is properly installed & running. See the attached image for the error.
   ![error](https://cloud.githubusercontent.com/assets/16477787/15564526/cdbf1338-2330-11e6-8842-1c6647445e1a.png)

I have also asked a question in stackoverflow related to showing 'video stored in HDFS over web browser'. If you want you can answer that too. http://stackoverflow.com/questions/37451685/accessing-video-stored-in-hdfs-over-http

**Comment by yeleaveszi** [comment]
Thank you for your issue.It seems that the project is not running correctly so that you see a 404 page.I think it is maven problem.I recommend you to use Eclipse for javaEE which has a maven plugin in it.It can help you to build the project quickly.Just import the project as a maven project and build it with the parameter _tomcat7:run_.
I tried again in my machine and there's no probolem.I can watch the video in the hdfs.
Moreover.If you are not familiar with maven.You can build the web project with eclipse or ideaj.Just copy java files ,web.xml,MyStream.html,and jar libs(http://pan.baidu.com/s/1gf33IpH) in the right place.Then you can do it.
Good luck.

**Comment by milind-pawar** [comment]
AbhilashAwasthi01:I am also facing the same issue as you mentioned. Did you got success in building this project ?

**Comment by AwasthiMaddy** [comment]
No I didn't. 
In my case I was able to generate the WAR File using Eclipse and I put that WAR File in the 'webapps' directory of tomcat, it was then automatically extracted & a folder with the name "HDFSVideoDemo" was created in it. But it didn't have the "MyStream.html" & hence when I type the link "http://localhost:8080/HDFSVideoDemo/MyStream.html" in my browser it shows the 404 error.

**Comment by milind-pawar** [comment]
Yes, I too follow the same process you mentioned and got same issue i.e.
404 Error in my case too. BTW thanks, I some how managed and choose an
alternate way i.e. created a new maven project and add all necessary
dependency and java files of that git project, now it works fine for me. :)

**Comment by AbhilashAwasthi01** [comment]
Can you please tell me in detail how to create a new maven project (As you have done).
The detailed steps that you took to run this project. 
P.S. I am not proficient in Java and tools like Eclipse.
